---
title: "Curriculum Vitae - Stephanie Copeland"
---

<a href = 'Copeland_Stephanie_CV.pdf' target = '_blank'>Click here for a PDF</a>

### Education

**University of California Santa Barbara** (Present)

- Graduate Student, 1st year

- P.I. Dr. Hillary Young

**University of New Hampshire**

- B.S. Biomedical Sciences, May 2018

- GPA - 3.62, University Scholar - *cum laude*

### Publications

D Orr, E Duge, **S Copeland**, Z Zilz, A Bui, C Motta, A Swei, and H Young. Context-dependent mediation of climate effects on larval tick survivorship by large herbivores in southcentral California. Submitted: Ecological Applications. (In Revision)

**S Copeland**, S Sambado, D Orr, A Swei, and H Young. Large Herbivore Removal and Climatic Gradient on Tick Abundance in southcentral California. In preparation for Ecological Applications.

D Orr, **S Copeland**, H Young. Four years of the Tejon Ranch Exclosure Experiment: plant, tick, and small vertebrate responses. In preparation for Ecology.

### Honors and Awards

**National Science Foundation’s Graduate Research Fellowship Program**

2021 Recipient

### Relevant Experience

- **Bulleted relevant projects completed under employment positions.**

**Lab Manager – Univ. of California Santa Barbara** (Spring 2020 – Summer 2021; P.I. Dr. Hillary Young)

- Tick survivorship responses to a prescribed grassland burn under stimulated grazing treatments at the Sedgwick Reserve (UC Natural Reserve System).

**Project Manager; Field Technician – Univ. of California Santa Barbara** (April 2019 – April 2020; P.I. Dr Hillary Young & Dr. Devyn Orr)

- Tick and tick-borne disease responses to large herbivore removal and subsequent cattle replacement along a topographical climatic gradient.

**Laboratory Technician – Tufts University** *Winter 2018 – Spring 2019; P.I. Dr. Sam Telford III & Dr. Heidi Goethert)

- Tick-borne pathogen screening from samples collected at hunting stations in Northeastern, United States.

**Summer Crew Leader; Field Technician – Univ. of New Hampshire** (Summers 2017, 2018; P.I. Dr. Matt Tarr & Erica Holm)

### Presentations

**Title:** “Population Structure and Dispersal of Prairie Warblers in Southern Maine and New Hampshire” (Spring 2018)
